# seed_db.py — One-time script to populate the professionals table in Supabase.
# Contains 40 healthcare providers across 19 specialties and 11 Italian cities.
# Run once: python scripts/seed_db.py (then run ingest_embeddings.py to generate vectors).

import os

from dotenv import load_dotenv
from supabase import create_client

load_dotenv()

url = os.environ.get("SUPABASE_URL")
key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")

if not url or not key:
    raise RuntimeError("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in environment.")

supabase = create_client(url, key)


professionals = [
    # --- Existing professionals (original seed) ---
    {
        "name": "Marco Rossi",
        "specialty": "Physiotherapist",
        "city": "Padova",
        "gender": "male",
        "supports_weight_kg": 100,
        "years_experience": 12,
        "clinical_summary": "Expert in post-operative hip and knee prosthesis rehabilitation. Capable of handling bariatric patients.",
    },
    {
        "name": "Giulia Bianchi",
        "specialty": "Nurse",
        "city": "Padova",
        "gender": "female",
        "supports_weight_kg": 60,
        "years_experience": 8,
        "clinical_summary": "Specialized in home care, medication administration, and wound dressing.",
    },
    {
        "name": "Alessandro Conte",
        "specialty": "Physiotherapist",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 95,
        "years_experience": 15,
        "clinical_summary": "Advanced physical therapy for elderly patients with mobility issues.",
    },
    {
        "name": "Francesca Neri",
        "specialty": "Geriatrician",
        "city": "Padova",
        "gender": "female",
        "supports_weight_kg": 80,
        "years_experience": 18,
        "clinical_summary": "Comprehensive geriatric assessment, frailty management, and medication review for older adults.",
    },
    {
        "name": "Luca Ferri",
        "specialty": "Nurse",
        "city": "Venezia",
        "gender": "male",
        "supports_weight_kg": 110,
        "years_experience": 10,
        "clinical_summary": "Home nursing for chronic patients, catheter care, and post-discharge monitoring.",
    },
    {
        "name": "Chiara Romano",
        "specialty": "Occupational Therapist",
        "city": "Padova",
        "gender": "female",
        "supports_weight_kg": 75,
        "years_experience": 9,
        "clinical_summary": "Helps elderly regain autonomy in daily living activities after hospitalization.",
    },
    {
        "name": "Davide Greco",
        "specialty": "Physiotherapist",
        "city": "Bologna",
        "gender": "male",
        "supports_weight_kg": 120,
        "years_experience": 14,
        "clinical_summary": "Neuromotor rehabilitation and transfer training for high-dependency home patients.",
    },
    {
        "name": "Elisa Fontana",
        "specialty": "Nurse",
        "city": "Torino",
        "gender": "female",
        "supports_weight_kg": 70,
        "years_experience": 7,
        "clinical_summary": "Skilled in injections, pressure ulcer prevention, and diabetes home management.",
    },
    {
        "name": "Matteo Bellini",
        "specialty": "Physiotherapist",
        "city": "Roma",
        "gender": "male",
        "supports_weight_kg": 90,
        "years_experience": 11,
        "clinical_summary": "Orthopedic rehabilitation with focus on knee, hip, and lumbar recovery.",
    },
    {
        "name": "Serena Gallo",
        "specialty": "Speech Therapist",
        "city": "Padova",
        "gender": "female",
        "supports_weight_kg": 65,
        "years_experience": 13,
        "clinical_summary": "Dysphagia and post-stroke speech rehabilitation for older adults at home.",
    },
    {
        "name": "Nicolo Ricci",
        "specialty": "Nurse",
        "city": "Padova",
        "gender": "male",
        "supports_weight_kg": 95,
        "years_experience": 6,
        "clinical_summary": "Night shifts, vital-sign monitoring, and support for complex home care plans.",
    },
    {
        "name": "Valentina Moretti",
        "specialty": "Psychologist",
        "city": "Firenze",
        "gender": "female",
        "supports_weight_kg": 60,
        "years_experience": 12,
        "clinical_summary": "Counseling for caregiver stress and emotional support for elderly chronic patients.",
    },
    {
        "name": "Andrea Rinaldi",
        "specialty": "Physiotherapist",
        "city": "Padova",
        "gender": "male",
        "supports_weight_kg": 130,
        "years_experience": 16,
        "clinical_summary": "Specialized in bariatric physiotherapy and safe mobilization in domestic settings.",
    },
    {
        "name": "Marta De Luca",
        "specialty": "Dietitian",
        "city": "Napoli",
        "gender": "female",
        "supports_weight_kg": 70,
        "years_experience": 10,
        "clinical_summary": "Nutritional plans for elderly patients with diabetes, renal conditions, and sarcopenia.",
    },
    {
        "name": "Stefano Caruso",
        "specialty": "Nurse",
        "city": "Padova",
        "gender": "male",
        "supports_weight_kg": 85,
        "years_experience": 9,
        "clinical_summary": "Wound care specialist with expertise in pressure injury and post-surgical management.",
    },
    {
        "name": "Irene Piras",
        "specialty": "Occupational Therapist",
        "city": "Cagliari",
        "gender": "female",
        "supports_weight_kg": 68,
        "years_experience": 8,
        "clinical_summary": "Home adaptation assessment and assistive device training for seniors.",
    },
    {
        "name": "Giorgio Marchetti",
        "specialty": "Geriatrician",
        "city": "Padova",
        "gender": "male",
        "supports_weight_kg": 90,
        "years_experience": 20,
        "clinical_summary": "Complex multimorbidity management and polypharmacy optimization in elderly care.",
    },
    {
        "name": "Laura Santini",
        "specialty": "Physiotherapist",
        "city": "Verona",
        "gender": "female",
        "supports_weight_kg": 88,
        "years_experience": 11,
        "clinical_summary": "Respiratory and mobility rehabilitation for frail older adults at home.",
    },
    {
        "name": "Federico Longo",
        "specialty": "Nurse",
        "city": "Genova",
        "gender": "male",
        "supports_weight_kg": 105,
        "years_experience": 13,
        "clinical_summary": "Experienced in home infusions, PICC line care, and palliative support.",
    },
    {
        "name": "Beatrice Villa",
        "specialty": "Physiotherapist",
        "city": "Padova",
        "gender": "female",
        "supports_weight_kg": 92,
        "years_experience": 10,
        "clinical_summary": "Fall-prevention and balance rehabilitation for elderly patients after hospitalization.",
    },
    # --- NEW specialties for broader coverage ---
    {
        "name": "Dr. Elena Conti",
        "specialty": "General Practitioner",
        "city": "Milano",
        "gender": "female",
        "supports_weight_kg": 80,
        "years_experience": 14,
        "clinical_summary": "Comprehensive primary care, chronic disease management, preventive check-ups, and home visits for non-ambulatory patients.",
    },
    {
        "name": "Dr. Paolo Ferrara",
        "specialty": "General Practitioner",
        "city": "Roma",
        "gender": "male",
        "supports_weight_kg": 90,
        "years_experience": 18,
        "clinical_summary": "Family medicine with focus on hypertension, diabetes screening, respiratory infections, and elderly wellness.",
    },
    {
        "name": "Dr. Anna Vitale",
        "specialty": "Psychiatrist",
        "city": "Milano",
        "gender": "female",
        "supports_weight_kg": 70,
        "years_experience": 16,
        "clinical_summary": "Treatment of depression, anxiety disorders, panic attacks, and insomnia. Medication management and supportive therapy.",
    },
    {
        "name": "Dr. Roberto Mancini",
        "specialty": "Psychiatrist",
        "city": "Roma",
        "gender": "male",
        "supports_weight_kg": 85,
        "years_experience": 20,
        "clinical_summary": "Mood disorders, bipolar disorder, PTSD, and addiction psychiatry. Home consultations for severe cases.",
    },
    {
        "name": "Dr. Sara Lombardi",
        "specialty": "Psychiatrist",
        "city": "Bologna",
        "gender": "female",
        "supports_weight_kg": 75,
        "years_experience": 12,
        "clinical_summary": "Anxiety, OCD, eating disorders, and cognitive-behavioral therapy integration with pharmacotherapy.",
    },
    {
        "name": "Dr. Giovanni Esposito",
        "specialty": "Neurologist",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 80,
        "years_experience": 15,
        "clinical_summary": "Migraine management, epilepsy, neuropathic pain, post-stroke follow-up, and dementia assessment.",
    },
    {
        "name": "Dr. Lucia Marino",
        "specialty": "Neurologist",
        "city": "Napoli",
        "gender": "female",
        "supports_weight_kg": 70,
        "years_experience": 11,
        "clinical_summary": "Multiple sclerosis, Parkinson's disease, chronic headache, and neurophysiological diagnostics.",
    },
    {
        "name": "Dr. Marco Trevisan",
        "specialty": "Cardiologist",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 100,
        "years_experience": 22,
        "clinical_summary": "Heart failure management, post-MI rehabilitation, arrhythmia monitoring, and home ECG assessment.",
    },
    {
        "name": "Dr. Claudia Ruggiero",
        "specialty": "Cardiologist",
        "city": "Torino",
        "gender": "female",
        "supports_weight_kg": 75,
        "years_experience": 13,
        "clinical_summary": "Hypertension control, cardiac risk assessment, echocardiography, and elderly cardiovascular prevention.",
    },
    {
        "name": "Dr. Simone Fabbri",
        "specialty": "Dermatologist",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 70,
        "years_experience": 10,
        "clinical_summary": "Acne, eczema, psoriasis, skin cancer screening, wound healing, and cosmetic dermatology consultations.",
    },
    {
        "name": "Dr. Alessia Colombo",
        "specialty": "Dermatologist",
        "city": "Firenze",
        "gender": "female",
        "supports_weight_kg": 65,
        "years_experience": 9,
        "clinical_summary": "Allergic dermatitis, chronic urticaria, mole mapping, and pediatric skin conditions.",
    },
    {
        "name": "Dr. Tommaso Gatti",
        "specialty": "Orthopedic Surgeon",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 120,
        "years_experience": 17,
        "clinical_summary": "Fracture management, joint replacement follow-up, sports injuries, and spinal assessment at home.",
    },
    {
        "name": "Dr. Federica Zanetti",
        "specialty": "Orthopedic Surgeon",
        "city": "Bologna",
        "gender": "female",
        "supports_weight_kg": 90,
        "years_experience": 14,
        "clinical_summary": "Post-surgical rehabilitation planning, osteoporosis treatment, and elderly fall-related fracture care.",
    },
    {
        "name": "Dr. Lara Pellegrini",
        "specialty": "Gynecologist",
        "city": "Milano",
        "gender": "female",
        "supports_weight_kg": 70,
        "years_experience": 12,
        "clinical_summary": "Prenatal care, menstrual disorders, menopause management, and cervical screening at home.",
    },
    {
        "name": "Dr. Andrea Silvestri",
        "specialty": "Pediatrician",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 50,
        "years_experience": 11,
        "clinical_summary": "Well-child visits, vaccination schedules, childhood infections, asthma, and developmental screening.",
    },
    {
        "name": "Dr. Martina Bianco",
        "specialty": "Pediatrician",
        "city": "Roma",
        "gender": "female",
        "supports_weight_kg": 45,
        "years_experience": 9,
        "clinical_summary": "Neonatal care, breastfeeding support, allergic conditions in children, and home fever management.",
    },
    {
        "name": "Dr. Filippo Rinaldi",
        "specialty": "Pulmonologist",
        "city": "Milano",
        "gender": "male",
        "supports_weight_kg": 85,
        "years_experience": 16,
        "clinical_summary": "COPD management, asthma control, home oxygen therapy, and post-COVID pulmonary rehabilitation.",
    },
    {
        "name": "Dr. Ginevra Costa",
        "specialty": "Endocrinologist",
        "city": "Milano",
        "gender": "female",
        "supports_weight_kg": 75,
        "years_experience": 13,
        "clinical_summary": "Diabetes management, thyroid disorders, hormonal imbalances, and metabolic syndrome treatment.",
    },
    {
        "name": "Dr. Riccardo Marini",
        "specialty": "Urologist",
        "city": "Roma",
        "gender": "male",
        "supports_weight_kg": 90,
        "years_experience": 15,
        "clinical_summary": "Prostate conditions, urinary tract infections, kidney stones, and catheter management at home.",
    },
    {
        "name": "Dr. Paola Santoro",
        "specialty": "Rheumatologist",
        "city": "Bologna",
        "gender": "female",
        "supports_weight_kg": 80,
        "years_experience": 14,
        "clinical_summary": "Rheumatoid arthritis, lupus, fibromyalgia, gout, and autoimmune disease management.",
    },
]


def seed() -> None:
    print("Seeding initial healthcare professionals...")
    response = supabase.table("professionals").insert(professionals).execute()
    inserted = len(response.data) if response.data else len(professionals)
    print(f"Successfully inserted {inserted} professionals.")


if __name__ == "__main__":
    seed()
